Pin the java paketo buildpack to v7.5.0
Looks like the latest version (v7.6.0) pushing a node app fails with:

```
    Paketo Buildpack for Maven 6.10.0
      https://github.com/paketo-buildpacks/maven
      Build Configuration:
        $BP_EXCLUDE_FILES                                                                 colon separated list of glob patterns, matched source files are removed
        $BP_INCLUDE_FILES                                                                 colon separated list of glob patterns, matched source files are included
        $BP_MAVEN_BUILD_ARGUMENTS  -Dmaven.test.skip=true --no-transfer-progress package  the arguments to pass to Maven
        $BP_MAVEN_BUILT_ARTIFACT   target/*.[ejw]ar                                       the built application artifact explicitly.  Supersedes $BP_MAVEN_BUILT_MODULE
        $BP_MAVEN_BUILT_MODULE                                                            the module to find application artifact in
        $BP_MAVEN_DAEMON_ENABLED   false                                                  use maven daemon
        $BP_MAVEN_POM_FILE         pom.xml                                                the location of the main pom.xml file, relative to the application root
        $BP_MAVEN_SETTINGS_PATH                                                           the path to a Maven settings file
        Creating cache directory /home/cnb/.m2
      Compiled Application: Contributing to layer
        Executing . --batch-mode -Dmaven.test.skip=true --no-transfer-progress package
    unable to invoke layer creator
    unable to contribute application layer
    error running build
    unable to start PTY
    exec: no command
    ERROR: failed to build: exit status 1
```

Co-authored-by: Georgi Sabev <georgethebeatle@gmail.com>